config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  namespace :api, defaults: { format: :json} do
    get "/search", to: "static_pages#search"
    resources :users, only: [:index, :create, :edit, :destroy, :show]
    resource :session, only: [:show, :create, :destroy]
    resources :shops do
      resources :items
    end
    resources :carts, only: [:index, :create, :show, :update]
    resources :orders, only: [:create, :edit, :destroy, :index, :show]

  end


  get "/auth/:provider/callback", to: "api/sessions#omniauth"
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  description    :text
#  qty            :integer          default(1), not null
#  price          :float            not null
#  shop_id        :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  main_image_url :string
#

class Item < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:name, :description]

  validates :name, :qty, :price, presence: true

  belongs_to :shop
  has_many :orders


end

app/controllers/api/items_controller.rb
module Api
  class ItemsController < ApiController

    before_action :require_signed_in!,
      only: [:new, :create, :edit, :update]
    before_action :require_owner, only: [:edit, :update]

    def index
      @items = Item.all
      render json: @items
    end

    def new
      @item = Shop.find(params[:shop_id]).items.new()
      render json: @item
    end

    def show
      @item = Item.find(params[:id])
      render json: @item
    end

    def create

      @item = Shop.find(params[:shop_id]).items.new(item_params)

      if @item.save
        render json: @item
      else
        render json: @item.errors.full_messages, status: :unprocessable_entity
      end
    end

    def edit
      @item = Item.find(params[:id])
      render json: @item
    end

    def update
      @item = Item.find(params[:id])

      if @item.update(item_params)
        render json: @item
      else
        render json: @item.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      @item = Item.find(params[:id])
      @item.destroy()
      redirect_to shop_url(params[:shop_id])
    end

    private

    def require_owner
      @item = Item.find(params[:id])
      unless @item.shop.owner_id == current_user.id
        redirect_to shop_item_url(@item.shop_id, @item.id)
      end
    end

    def item_params
      params.require(:item).permit(:name, :price, :qty, :description, :main_image_url)
    end
  end
end

app/views/items/new.html.erb
<h1>Register a new item for sale!</h1>

<form action="<%= shop_items_url %>" method="post">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <label>Item name:
    <input type="text" name="item[name]" value="<%= @item.name %>">
  </label>
  <br><br>

  <label>Description
    <textarea name="item[description]"></textarea>
  </label>
  <br><br>

  <label>Price
    <input type="text" name="item[price]" value="<%= @item.price %>">
  </label>
  <br><br>

  <label>Quantity in Stock
    <input type="text" name="item[qty]" value="<%= @item.qty %>">
  </label>

  <button class="submit">Submit</button>

</form>